<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Damilola Sule">
<meta name="dcterms.date" content="2026-05-28">

<title>MaxDiff Analysis of MSBA Class Preferences – Damilola Sule Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b678371c533e4a3479052e9903027f9e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Damilola Sule Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../sports.html"> 
<span class="menu-text">Sports &amp; Analytics</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#quick-intro-to-maxdiff" id="toc-quick-intro-to-maxdiff" class="nav-link active" data-scroll-target="#quick-intro-to-maxdiff">Quick Intro to MaxDiff</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Damilola Sule </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="quick-intro-to-maxdiff" class="level2">
<h2 class="anchored" data-anchor-id="quick-intro-to-maxdiff">Quick Intro to MaxDiff</h2>
<p>Before getting into the analysis, this short video gives a quick overview of how MaxDiff (Best-Worst Scaling) works and why it is often preferred over traditional rating scales.</p>
<iframe width="700" height="400" src="https://www.youtube.com/embed/5hQkQx8pG2A" title="MaxDiff Overview" frameborder="0" allowfullscreen="">
</iframe>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This assignment explores a survey method called <strong>MaxDiff</strong> (also known as <em>Best-Worst Scaling</em>), which is designed to measure how strongly people prefer certain items over others. Instead of asking respondents to rate items on a scale from 1–10, MaxDiff presents a small group of options at a time and asks people to choose the <em>best</em> and <em>worst</em> item from the set. In our case, each screen shows four UCSD Rady MSBA core classes, and respondents repeatedly pick the class they would most want to take and least want to take.</p>
<p>The reason MaxDiff is useful is that humans are usually much better at making comparisons than assigning consistent numeric ratings. With rating scales, people interpret numbers differently — one person’s “8” might be another person’s “5.” Some people also avoid extreme ratings altogether. MaxDiff gets around this problem by forcing respondents to make trade-offs. Every choice gives information about relative preference, which tends to produce cleaner and more reliable data.</p>
<p>For this assignment, the goal is to estimate student preferences for the 10 MSBA core classes using three different methods. The first approach is a simple <strong>counts analysis</strong>, where we calculate how often each class was chosen as “best” minus how often it was chosen as “worst.” The second approach uses a <strong>multinomial logit (MNL)</strong> model estimated with <strong>maximum likelihood</strong>, which gives a more formal statistical model of choice behavior. Finally, we estimate the same MNL model using a <strong>Bayesian</strong> approach with a Metropolis-Hastings MCMC sampler.</p>
<p>Even though these methods are different, I expect them to produce similar overall rankings of the classes. The main differences should come from how they measure the strength of preferences and how they represent uncertainty. The counts analysis will probably give a quick intuitive summary, while the likelihood and Bayesian approaches should provide more statistically grounded estimates.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>The main dataset for this assignment is <code>maxdiff_design_and_choices.csv</code>, which contains the survey design and respondent choices from the MaxDiff study. Each row represents a single item shown on a particular survey screen. The columns include:</p>
<ul>
<li><code>Record ID</code>: anonymized respondent identifier</li>
<li><code>Task</code>: the survey screen number for that respondent</li>
<li><code>Position</code>: the location of the item on the screen (1–4)</li>
<li><code>Item</code>: which of the 10 MSBA core classes was shown</li>
<li><code>Response</code>: coded as <code>1</code> if the item was selected as “best,” <code>-1</code> if selected as “worst,” and <code>0</code> otherwise</li>
</ul>
<p>I also read in <code>maxdiff_item_labels.csv</code>, which maps the item numbers to the actual class names. This makes the results easier to interpret later in the analysis.</p>
<p>Before estimating any models, I checked a few basic descriptives and validated the structure of the dataset. After filtering to the valid MaxDiff tasks, the dataset contains 85 respondents, with each respondent completing 8 tasks. Each task contains 4 items, and there are 10 total classes in the study.</p>
<p>As a sanity check, I verified that every task contains exactly one “best” choice (<code>Response = 1</code>), exactly one “worst” choice (<code>Response = -1</code>), and the remaining two items coded as <code>0</code>. This is important because the multinomial logit model assumes the MaxDiff responses are structured correctly. I coded this check directly in R to confirm that the valid tasks satisfy these conditions.</p>
<p>I also counted how many times each class appeared across the survey. Since MaxDiff experiments are typically designed to balance item exposure, the appearance counts for the 10 classes were all relatively similar. This helps ensure that no class has an unfair advantage simply because it appeared more often than the others.</p>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<p>The simplest way to analyze MaxDiff data is with a <strong>counts analysis</strong>. The idea is to compare how often each class was selected as the “best” option versus how often it was selected as the “worst” option, relative to the number of times it appeared in the survey.</p>
<p><span class="math display">\[
\text{score}_j = \%\text{best}_j - \%\text{worst}_j
\]</span></p>
<p>A score close to +1 means a class was almost always selected as “best” when shown, while a score close to -1 means it was usually selected as “worst.” Scores near 0 suggest the class was either more neutral or more mixed across respondents.</p>
<p>Compared to the later MNL models, the counts analysis is much simpler and easier to interpret. It does not estimate latent utilities or formally model uncertainty, but it provides a strong first look at the overall ranking structure in the data.</p>
<p>To better understand the ranking of preferences across the 10 classes, I summarized the counts results in both a ranked table and a horizontal bar chart.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Counts Analysis Ranking of MSBA Core Classes</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 50%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">Item</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Times Shown</th>
<th style="text-align: right;">Times Best</th>
<th style="text-align: right;">Times Worst</th>
<th style="text-align: right;">% Best</th>
<th style="text-align: right;">% Worst</th>
<th style="text-align: right;">Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.536</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">0.493</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">MGTA 453 Business Analytics (Fall with August)</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0.344</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.141</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">0.377</td>
<td style="text-align: right;">0.257</td>
<td style="text-align: right;">0.120</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">MGTA 452 Large Data (Fall with Hansen)</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.279</td>
<td style="text-align: right;">0.217</td>
<td style="text-align: right;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">MGTA 454 Capstone Project (Spring with Advisor)</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">0.265</td>
<td style="text-align: right;">0.254</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">MGTA 464 SQL (Summer with Nijs)</td>
<td style="text-align: right;">274</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">0.201</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">-0.004</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td style="text-align: right;">266</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.207</td>
<td style="text-align: right;">-0.120</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">0.330</td>
<td style="text-align: right;">-0.209</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">0.158</td>
<td style="text-align: right;">0.371</td>
<td style="text-align: right;">-0.213</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td style="text-align: right;">267</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">0.124</td>
<td style="text-align: right;">0.416</td>
<td style="text-align: right;">-0.292</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/counts-bar-chart-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The counts analysis provides a quick first look at student preferences across the 10 MSBA core classes. Classes with positive scores were selected as “best” more often than “worst,” while classes with negative scores were selected as “worst” more frequently.</p>
<p>From the results, MGTA 495 (Marketing Analytics) and MGTA 453 (Business Analytics) appear to be among the most preferred classes because they received the strongest positive scores. In contrast, MGTA 444 (Analytics Consulting) and MGTA 403 (AI Math, Programming, &amp; Analytics) received more negative scores and were more commonly selected as the “worst” option.</p>
<p>The confidence intervals also help show the uncertainty around the estimated scores. Some classes are clearly separated from the rest, while others have overlapping intervals, suggesting their rankings may not be meaningfully different. Overall, the counts analysis already reveals a fairly clear ranking structure before moving into the more formal multinomial logit models.</p>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<p>To move from the simple counts analysis to a multinomial logit (MNL) model, the MaxDiff responses need to be translated into choice observations. The MNL framework models the probability that a respondent chooses one item over the others based on an underlying utility value assigned to each item.</p>
<p>In the model, each class (j) receives a utility coefficient (_j). Higher values of (_j) correspond to classes that respondents generally prefer more. For a MaxDiff task containing four classes, the probability that a particular class is selected as the “best” option follows the standard soft-max form from the week 5 conjoint/MNL lecture:</p>
<p><span class="math display">\[
P(\text{best} = b) =
\frac{\exp(\beta_b)}
{\exp(\beta_a) + \exp(\beta_b) + \exp(\beta_c) + \exp(\beta_d)}
\]</span></p>
<p>After the “best” item is removed, the respondent then selects the “worst” option from the remaining three classes. In MaxDiff modeling, the worst choice can be treated as a choice among the remaining items with utilities flipped in sign. This gives:</p>
<p><span class="math display">\[
P(\text{worst} = c \mid \text{best} = b) =
\frac{\exp(-\beta_c)}
{\exp(-\beta_a) + \exp(-\beta_c) + \exp(-\beta_d)}
\]</span></p>
<p>This means that every MaxDiff task actually contributes <em>two</em> MNL observations: one for the best choice from the full set of four items, and one for the worst choice from the remaining three items.</p>
<p>One important issue in the MNL model is <strong>identifiability</strong>. Because the soft-max probabilities do not change if the same constant is added to every utility coefficient, only relative differences in utility can be estimated. As a result, only (J - 1) coefficients are identified. Since there are 10 classes in this study, only 9 coefficients can be freely estimated. To solve this, I normalize the model by fixing one class as the reference level and setting:</p>
<p><span class="math display">\[
\beta_1 = 0
\]</span></p>
<p>The remaining coefficients (<em>2, , </em>{10}) are then interpreted relative to this baseline class.</p>
<p>Before estimating the likelihood, I reshaped the MaxDiff data into a task-level structure that is easier to loop through in the MNL likelihood function. For each task, I stored:</p>
<ul>
<li>the four items shown on the screen</li>
<li>which item was selected as “best”</li>
<li>which item was selected as “worst”</li>
</ul>
<p>This structure makes it straightforward to iterate over tasks and compute the contribution of each best and worst choice to the overall log-likelihood.</p>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<p>Now that the MaxDiff data is organized at the task level, I can estimate the multinomial logit model using maximum likelihood. The idea is to find the values of the utility coefficients, (), that make the observed best and worst choices most likely.</p>
<p>For each task, the log-likelihood includes two pieces: the probability of the item chosen as “best,” and the probability of the item chosen as “worst” after flipping the utilities and removing the best item.</p>
<p><span class="math display">\[
\ell(\boldsymbol{\beta}) =
\sum_{\text{tasks}}
\Big[
\beta_{j^*_b}
-
\log \sum_{j \in \text{shown}} \exp(\beta_j)
-
\beta_{j^*_w}
-
\log \sum_{j \in \text{shown} \setminus \{j^*_b\}} \exp(-\beta_j)
\Big]
\]</span></p>
<p>Here, (j^*_b) is the class picked as best and (j^*_w) is the class picked as worst. Since MNL utilities are only identified up to a constant, I set (_1 = 0) and estimate the remaining 9 coefficients.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>MNL Maximum Likelihood Estimates</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 53%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">Item</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Beta Estimate</th>
<th style="text-align: right;">Standard Error</th>
<th style="text-align: right;">Share of Preference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td style="text-align: right;">1.630</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">0.284</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">MGTA 453 Business Analytics (Fall with August)</td>
<td style="text-align: right;">0.744</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">0.117</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td style="text-align: right;">0.656</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">0.107</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">MGTA 452 Large Data (Fall with Hansen)</td>
<td style="text-align: right;">0.555</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.097</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">MGTA 454 Capstone Project (Spring with Advisor)</td>
<td style="text-align: right;">0.443</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">MGTA 464 SQL (Summer with Nijs)</td>
<td style="text-align: right;">0.438</td>
<td style="text-align: right;">0.137</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.137</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td style="text-align: right;">-0.067</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">0.052</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td style="text-align: right;">-0.239</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">0.044</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/mle-share-plot-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of Counts Ranking and MLE Ranking</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 48%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Item</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Counts Rank</th>
<th style="text-align: right;">Counts Score</th>
<th style="text-align: right;">MLE Rank</th>
<th style="text-align: right;">Beta Estimate</th>
<th style="text-align: right;">Share of Preference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.493</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.630</td>
<td style="text-align: right;">0.284</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">MGTA 453 Business Analytics (Fall with August)</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.744</td>
<td style="text-align: right;">0.117</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.656</td>
<td style="text-align: right;">0.107</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">MGTA 452 Large Data (Fall with Hansen)</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.555</td>
<td style="text-align: right;">0.097</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">MGTA 454 Capstone Project (Spring with Advisor)</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.443</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">MGTA 464 SQL (Summer with Nijs)</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-0.004</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.438</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">-0.120</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">-0.209</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">-0.213</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">-0.067</td>
<td style="text-align: right;">0.052</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-0.292</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-0.239</td>
<td style="text-align: right;">0.044</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The MNL estimates tell a similar story to the counts analysis, but in a more formal model-based way. The raw () values are useful because they show each class’s estimated utility relative to the reference class, but the shares of preference are easier to interpret because they add up to 1 across all 10 classes.</p>
<p>Overall, I expect the MLE ranking to be very close to the counts ranking. If there are small differences, they likely come from the fact that the MNL model uses the full choice structure of each task instead of only summarizing best and worst counts separately. In other words, the MNL model pays attention to which classes appeared together on each screen, while the counts analysis is more of a direct descriptive summary.</p>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<p>For the Bayesian version, I estimate the same MNL model, but instead of only finding one best-fitting value of (), I estimate a full posterior distribution. This lets me see both the likely value of each class utility and the uncertainty around it.</p>
<p>Using Bayes’ rule, the posterior is:</p>
<p><span class="math display">\[
\pi(\boldsymbol{\beta} \mid \boldsymbol{y})
\propto
L(\boldsymbol{\beta}) \cdot \pi(\boldsymbol{\beta})
\]</span></p>
<p>I use a weakly informative normal prior:</p>
<p><span class="math display">\[
\boldsymbol{\beta} \sim N(\boldsymbol{0}, 10I)
\]</span></p>
<p>This prior keeps the estimates from becoming extreme, but it is still wide enough to let the data mostly drive the results.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1285</code></pre>
</div>
</div>
<p>The final acceptance rate should ideally be around 25% to 40%. If the acceptance rate is much lower than that, I would reduce the step size. If it is much higher, I would increase the step size. This tuning matters because a step size that is too small moves too slowly, while a step size that is too large gets rejected too often.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/bayes-trace-plots-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The trace plots are used to check whether the sampler is mixing reasonably well. Ideally, the chains should look like a “fuzzy caterpillar” instead of showing a steady upward or downward drift. In this run, I use the first 25% of draws as burn-in and base the posterior summaries only on the remaining draws.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Bayesian MNL Posterior Estimates</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 48%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">Item</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Posterior Mean Beta</th>
<th style="text-align: right;">Beta 2.5%</th>
<th style="text-align: right;">Beta 97.5%</th>
<th style="text-align: right;">Posterior Mean Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td style="text-align: right;">1.640</td>
<td style="text-align: right;">1.363</td>
<td style="text-align: right;">1.917</td>
<td style="text-align: right;">0.284</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">MGTA 453 Business Analytics (Fall with August)</td>
<td style="text-align: right;">0.757</td>
<td style="text-align: right;">0.494</td>
<td style="text-align: right;">1.013</td>
<td style="text-align: right;">0.117</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td style="text-align: right;">0.672</td>
<td style="text-align: right;">0.423</td>
<td style="text-align: right;">0.969</td>
<td style="text-align: right;">0.108</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">MGTA 452 Large Data (Fall with Hansen)</td>
<td style="text-align: right;">0.560</td>
<td style="text-align: right;">0.292</td>
<td style="text-align: right;">0.822</td>
<td style="text-align: right;">0.096</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">MGTA 454 Capstone Project (Spring with Advisor)</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.732</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">MGTA 464 SQL (Summer with Nijs)</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.719</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td style="text-align: right;">0.255</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.520</td>
<td style="text-align: right;">0.071</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td style="text-align: right;">-0.070</td>
<td style="text-align: right;">-0.339</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.051</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td style="text-align: right;">-0.231</td>
<td style="text-align: right;">-0.542</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.044</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/bayes-share-plot-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of MLE and Bayesian MNL Results</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 42%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Item</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">MLE Beta</th>
<th style="text-align: right;">MLE SE</th>
<th style="text-align: right;">MLE Share</th>
<th style="text-align: right;">Posterior Mean Beta</th>
<th style="text-align: right;">Beta 2.5%</th>
<th style="text-align: right;">Beta 97.5%</th>
<th style="text-align: right;">Posterior Mean Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td style="text-align: right;">1.630</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">0.284</td>
<td style="text-align: right;">1.640</td>
<td style="text-align: right;">1.363</td>
<td style="text-align: right;">1.917</td>
<td style="text-align: right;">0.284</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">MGTA 453 Business Analytics (Fall with August)</td>
<td style="text-align: right;">0.744</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">0.757</td>
<td style="text-align: right;">0.494</td>
<td style="text-align: right;">1.013</td>
<td style="text-align: right;">0.117</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td style="text-align: right;">0.656</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">0.672</td>
<td style="text-align: right;">0.423</td>
<td style="text-align: right;">0.969</td>
<td style="text-align: right;">0.108</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">MGTA 452 Large Data (Fall with Hansen)</td>
<td style="text-align: right;">0.555</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.560</td>
<td style="text-align: right;">0.292</td>
<td style="text-align: right;">0.822</td>
<td style="text-align: right;">0.096</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">MGTA 454 Capstone Project (Spring with Advisor)</td>
<td style="text-align: right;">0.443</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.732</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">MGTA 464 SQL (Summer with Nijs)</td>
<td style="text-align: right;">0.438</td>
<td style="text-align: right;">0.137</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.719</td>
<td style="text-align: right;">0.087</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.137</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.255</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.520</td>
<td style="text-align: right;">0.071</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.056</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td style="text-align: right;">-0.067</td>
<td style="text-align: right;">0.139</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">-0.070</td>
<td style="text-align: right;">-0.339</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.051</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td style="text-align: right;">-0.239</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">-0.231</td>
<td style="text-align: right;">-0.542</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.044</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The Bayesian results should be very close to the maximum likelihood results because both methods are estimating the same underlying MNL model. The main difference is that the Bayesian version produces a full distribution of possible values for each (), rather than only a point estimate and standard error.</p>
<p>In my interpretation, the posterior mean betas should line up closely with the MLE beta estimates. The credible intervals should also tell a similar story to the MLE standard errors. If some estimates differ slightly, that is likely due to the weakly informative prior and the randomness of the MCMC sampler. The prior gently pulls extreme estimates toward zero, while the MCMC sampler introduces simulation noise because it approximates the posterior using draws rather than solving for one exact optimum.</p>
<p>Overall, the Bayesian MNL model gives a similar ranking of classes as the MLE model, but it makes uncertainty more visible. I found the posterior shares especially helpful because they are easier to interpret than raw utility coefficients and they show how much preference each class receives relative to the others.</p>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<p>After estimating preferences using the counts analysis, the MLE MNL model, and the Bayesian MNL model, I combined all three approaches into a single comparison table. This makes it easier to see where the methods agree and where small differences appear in the rankings.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of Counts, MLE, and Bayesian Rankings</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 48%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Item</th>
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Counts Score</th>
<th style="text-align: right;">Counts Rank</th>
<th style="text-align: right;">MLE Share</th>
<th style="text-align: right;">MLE Rank</th>
<th style="text-align: right;">Bayes Share</th>
<th style="text-align: right;">Bayes Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">MGTA 495 Marketing Analytics (Spring with Yavorsky)</td>
<td style="text-align: right;">0.493</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.284</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.284</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: left;">MGTA 453 Business Analytics (Fall with August)</td>
<td style="text-align: right;">0.141</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td style="text-align: right;">0.120</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.108</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">MGTA 452 Large Data (Fall with Hansen)</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8</td>
<td style="text-align: left;">MGTA 454 Capstone Project (Spring with Advisor)</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">MGTA 464 SQL (Summer with Nijs)</td>
<td style="text-align: right;">-0.004</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: left;">MGTA 457 Biz. Intelligence Systems (Fall with Schibler)</td>
<td style="text-align: right;">-0.120</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">MGTA 403 AI Math, Prog., &amp; Analytics (Summer with Nijs)</td>
<td style="text-align: right;">-0.209</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.056</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">MGTA 451 Marketing/Finance/Operations (Summer with Wilbur/Buti/Shin)</td>
<td style="text-align: right;">-0.213</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.052</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">MGTA 444 Analytics Consulting (Winter with Peterson)</td>
<td style="text-align: right;">-0.292</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.044</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/comparison-visuals-1.png" class="img-fluid figure-img" width="1440"></p>
</figure>
</div>
</div>
</div>
<p>Overall, the three methods produce very similar rankings of the MSBA classes, especially for the classes at the very top and bottom of the list. Classes like MGTA 495 and MGTA 453 consistently appear near the top across all methods, while classes such as MGTA 444 and MGTA 403 tend to remain near the bottom. This consistency is reassuring because it suggests that the underlying preference signal in the data is fairly strong.</p>
<p>Most of the differences between methods appear in the middle of the rankings, where several classes have relatively similar utility levels. In these cases, small amounts of statistical noise or modeling differences can easily flip the order of two nearby classes. The counts analysis is the most direct and descriptive approach, while the MNL models estimate preferences through the full probabilistic choice process.</p>
<p>One major advantage of the MNL approach over the counts analysis is that it uses more information from each task. In the counts analysis, only the best and worst selections matter directly. In contrast, the MNL model also learns from the items that were <em>shown but not selected</em>. Every item on the screen contributes information about relative preference, which generally leads to more statistically efficient estimates.</p>
<p>The Bayesian model adds another layer by making uncertainty easier to interpret. Instead of producing only a point estimate and standard error, the Bayesian approach gives a full posterior distribution for every parameter and every derived quantity. For example, obtaining credible intervals for the shares of preference is straightforward: each MCMC draw can be transformed through the soft-max function, and the resulting distribution of shares can be summarized directly with percentiles. Doing this with MLE estimates is possible, but typically requires extra approximation methods such as the delta method.</p>
<p>Overall, all three approaches tell a very similar story about student preferences, but they differ in complexity, interpretation, and how they represent uncertainty.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Overall, all three methods told a pretty similar story about which MSBA classes students preferred most. Classes like MGTA 495 (Marketing Analytics) and MGTA 453 (Business Analytics) consistently ranked near the top across the counts analysis, MLE model, and Bayesian model. Meanwhile, classes like MGTA 444 and MGTA 403 tended to rank lower. One thing I found interesting was that some of the more technical courses were not necessarily the most preferred, even though they are probably some of the most useful long-term.</p>
<p>The three methods mainly differed in how much statistical detail they provided. The counts analysis was the easiest to understand and gave a quick summary of which classes students liked or disliked most. I could see this being useful for a dashboard or fast overview. The MLE multinomial logit model felt more statistically rigorous because it explicitly modeled the choice process instead of just counting selections. It also used information from the items that were shown but not picked.</p>
<p>The Bayesian model ended up being the most interesting to me because it made uncertainty easier to visualize. Instead of getting only one estimate, the Bayesian approach gave a full distribution for each parameter and the preference shares. I also thought it was cool seeing how the Metropolis-Hastings sampler gradually stabilized once the step size was tuned reasonably well.</p>
<p>There are definitely some limitations to the analysis. The responses come from a self-selected group of MSBA students, so the results may not generalize beyond this program. Preferences could also depend on things like students’ backgrounds, career goals, current workload, or whether they had already heard good or bad things about a class before taking the survey.</p>
<p>If I had more time, I would probably explore individual-level preference differences instead of only estimating one average preference for everyone. It would also be interesting to compare preferences across students interested in different career paths, like marketing analytics versus data science or consulting.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>